name: Notify on PR Creation

on:
  pull_request:
    types: [opened]

jobs:
  notify-email:
    runs-on: ubuntu-latest

    steps:
      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          to: "jayant.jose@gmail.com"
          subject: "New Pull Request Created"
          body: |
            A new pull request has been created!
            Title: ${{ github.event.pull_request.title }}
            URL: ${{ github.event.pull_request.html_url }}
          from: "jayant.jose@gmail.com"
          server_address: "smtp.gmail.com"
          server_port: 587
          username: "jayant.jose@gmail.com"
          password: "msxxqktzknioxkuj"
          secure: true
      - name: Confirm Email Sent
        run: echo "Email action completed"